---
# ClusterIP Service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama-system
  labels:
    app: ollama
    component: service
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  selector:
    app: ollama
    component: model-service

---
# NodePort Service for external access
apiVersion: v1
kind: Service
metadata:
  name: ollama-nodeport
  namespace: ollama-system
  labels:
    app: ollama
    component: external-service
spec:
  type: NodePort
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 30434  # 可以修改为其他端口
    protocol: TCP
    name: http
  selector:
    app: ollama
    component: model-service

---
# Headless Service for StatefulSet (if needed)
apiVersion: v1
kind: Service
metadata:
  name: ollama-headless
  namespace: ollama-system
  labels:
    app: ollama
    component: headless-service
spec:
  clusterIP: None
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  selector:
    app: ollama
    component: model-service