---
# PersistentVolumeClaim for Ollama models
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: ollama-system
  labels:
    app: ollama
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard" # 根据你的 K8s 集群调整

---
# PersistentVolumeClaim for Ollama cache
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cache-pvc
  namespace: ollama-system
  labels:
    app: ollama
    component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard" # 根据你的 K8s 集群调整